# luci-app-aprx

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for aprx (APRS iGate/Digipeater)
LUCI_DEPENDS:=+aprx
LUCI_PKGARCH:=all

PKG_VERSION:=1.0.0

include $(TOPDIR)/feeds/luci/luci.mk

PKG_MAINTAINER:=Patrick Tudor <openwrt@ptudor.net>

# call BuildPackage - OpenWrt buildroot signature
