#  vi /home/ptudor/openwrt/feeds/luci/applications/luci-app-galmon/Makefile 
# luci-app-galmon

#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Galmon.eu ubxtool
LUCI_DEPENDS:=+galmon
LUCI_PKGARCH:=all

PKG_VERSION:=1.0.0

#include ../../luci.mk
#include ../../../luci/luci.mk
include $(TOPDIR)/feeds/luci/luci.mk


#PKG_MAINTAINER:=Patrick Tudor <openwrt@ptudor.net>

# call BuildPackage - OpenWrt buildroot signature
