#!/bin/sh /etc/rc.common
 
USE_PROCD=1
 
START=89
STOP=13
 
validate_galmon_config()
{
	uci_validate_section galmon ubxtool \
		'gps:bool' \
		'galileo:bool' \
		'glonass:bool' \
		'beidou:bool' \
		'sbas:bool' \
		'port:string' \
		'station:uinteger' \
		'destination:or(string,ip6addr,ip4addr)' \
		'remark:string' \
		'owner:string'
}

append_arg() {
	local cfg="$1"
	local var="$2"
	local opt="$3"
	local def="$4"
	local val

	config_get val "$cfg" "$var"
	if [ -n "$val" ] || [ -n "$def" ]; then
		procd_append_param command "$opt" "${val:-$def}"
	fi
}

append_bool() {
	local cfg="$1"
	local var="$2"
	local opt="$3"
	local def="$4"
	local val

	config_get_bool val "$cfg" "$var" "$def"
	[ "$val" = 1 ] && procd_append_param command "$opt"
}

service_triggers() {
    procd_add_reload_trigger "galmon"
    procd_open_validate
    validate_galmon_config
    procd_close_validate
}

start_instance() {
    local cfg="$1"
 
    procd_open_instance
 
    procd_set_param file /etc/config/galmon
    procd_set_param command /usr/bin/ubxtool
    append_bool "$cfg" gps "-g"
    append_bool "$cfg" galileo "-e"
    append_bool "$cfg" glonass "-r"
    append_bool "$cfg" beidou "-c"
    append_bool "$cfg" sbas "--sbas"
    append_arg "$cfg" port "--port"
    append_arg "$cfg" station "--station"
    append_arg "$cfg" destination "--destination"
    append_arg "$cfg" owner "--owner"
    append_arg "$cfg" remark "--remark"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}

start_service() {
	config_load galmon
	start_instance ubxtool
}
